# Generated by Django 5.0.7 on 2025-02-16 15:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ستون')),
                ('data_type', models.CharField(choices=[('char', 'متن'), ('int', 'عدد'), ('date', 'تاریخ'), ('bool', 'بولین')], max_length=50, verbose_name='نوع داده')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('major', models.CharField(max_length=100, verbose_name='رشته')),
                ('father_job', models.CharField(max_length=100, verbose_name='شغل پدر')),
                ('path', models.CharField(max_length=50, verbose_name='مسیر (آغاز/پرواز)')),
                ('address', models.TextField(verbose_name='آدرس خانه')),
                ('card_number', models.CharField(max_length=20, verbose_name='شماره کارت')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('Description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_job', models.CharField(blank=True, max_length=100, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_type', models.CharField(choices=[('visitor', 'بازدیدکننده'), ('admin', 'ادمین'), ('flight_student', 'دانشجوی پرواز'), ('beginner_student', 'دانشجو آغاز')], default='visitor', max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('national_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
                ('teaching_assistants', models.ManyToManyField(blank=True, related_name='assisted_classes', to=settings.AUTH_USER_MODEL, verbose_name='دستیاران آموزشی (تی\u200cای\u200cها)')),
                ('students', models.ManyToManyField(related_name='enrolled_classes', to='account.student', verbose_name='دانش\u200cآموزان')),
            ],
            options={
                'verbose_name': 'کلاس روبیکمپی',
                'verbose_name_plural': 'کلاس\u200cهای روبیکمپ',
            },
        ),
        migrations.CreateModel(
            name='DynamicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_char', models.CharField(blank=True, max_length=255, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dynamiccolumn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, related_name='uploaded_files', to='account.student')),
            ],
        ),
    ]
