# Generated by Django 5.0.7 on 2025-02-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.TextField(null=True, verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
